- name: Get PGSQL version
  command: psql --version
  changed_when: false
  check_mode: false
  register: pgsql_version_check
  tags:
    - always

- name: Set PGSQL version
  set_fact:
    pgsql_version: "{{ pgsql_version_check['stdout'].split()[-1][:3] }}"
  tags:
    - always
