- name: Stop PostgreSQL
  service:
    name: postgresql-{{ pgsql_version }}
    state: stopped

- name: Clear out data directory
  shell: rm -rf {{ pgsqlrep_data_path }}/*

- name: Create base backup
  command: pg_basebackup -X stream -D {{ pgsqlrep_data_path }} -h {{ pgsqlrep_master_address }} -U {{ pgsqlrep_user }}
  become: true
  become_user: postgres

- name: Create recovery.conf
  template:
    src: recovery.conf.j2
    dest: "{{ pgsqlrep_data_path }}/recovery.conf"
    owner: postgres
    group: postgres
    mode: '0644'

- name: Enable hot standby
  lineinfile:
    state: present
    backup: true
    dest: "{{ pgsqlrep_data_path }}/postgresql.conf"
    regexp: '^#?hot_standby = \w+(\s+#.*)'
    line: 'hot_standby = yes\1'
    backrefs: true
  become: true
  become_user: postgres

- name: Start and enable PostgreSQL
  service:
    name: postgresql-{{ pgsql_version }}
    state: started
    enabled: true
