---
# Tasks for configuring PostgreSQL server.

- name: init postgresql (el-only)
  command: '{{ pg_initdb_command }}'
  args:
    creates: /var/lib/pgsql/9.6/data/PG_VERSION
  when: ansible_os_family == "RedHat"

- name: Make sure PostgreSQL is started
  service:
    name: '{{ postgres_init_name }}'
    state: started
  register: postgresql_start

- name: Wait for PostgreSQL to start if it wasnt
  wait_for:
    host: localhost
    port: 5432
  when: postgresql_start is changed



